### PR TITLE
[WIP] Implicit SInDy

### PR DESCRIPTION
**Pull request by AlCap23**
Working with sparse basis of QR decomposition rather than ADM;
Works better for now

### CODE REVIEW

**Comment by AlCap23** [comment]
Yeah, right now that's just for testing. Working the last details out. Can we solve nonlinear systems for the ivs right now in Modeling Toolkit?

**Comment by ChrisRackauckas** [comment]
>Can we solve nonlinear systems for the ivs right now in Modeling Toolkit?

Symbolically? That's a very difficult problem.

**Comment by AlCap23** [comment]
Ah, not ivs but rather differential states. Won't be easier. Just thinking about how to generate a problem from the isindy algorithm. Right now it returns a basis.

**Comment by AlCap23** [comment]
Better implementation via #36

**Pull request closed without merging**
