### PR TITLE
[WIP] HAVOK

### PR DESCRIPTION
**Pull request by AlCap23**
See https://de5337a9-e467-4569-8f4a-5f1c6678b48f.filesusr.com/ugd/c50953_aadbab271c3641848eef82169f2c78c8.pdf

Add prototype.

Works with the right settings. Still need to get this into an ODE system for simulation.

Tweak SINDy for this.

### CODE REVIEW

**Comment by AlCap23** [comment]
@ChrisRackauckas Do you think we should / could put this out as an DDE ?

Btw the zhat is actually dzhat and fits perfectly :)

**Comment by ChrisRackauckas** [comment]
It would be more numerically stable as a DDE: you could in theory have the time delayed observables as other terms in a larger ODE, but then they could in theory drift over time.

**Comment by AlCap23** [comment]
I think this can be merged this into master as an example.

I'll open an issue for the DDE conversion. 

Do you think this should be handled in DataDrivenDiffEq or MTK ?

**Comment by ChrisRackauckas** [comment]
I need to add DDEs to MTK, but I should do that soon.

**Pull request merged**
